### ISSUE TITLE
[data] WASH Access and Use in Nabilatuk District, Uganda: A Cross-Sectional Study of Different Data Collection Methods

### ISSUE THREAD

**Issue by mianzg** [openwashdata/data#26]
https://www.mdpi.com/2673-947X/3/2/8

**Comment by larnsce** [comment]
Data available here: https://data.mendeley.com/datasets/6yty843zvk/1

**Comment by larnsce** [comment]
@margauxgo, let's use this dataset as your first dataset for preparation and publishing. We will work with it in our workshop on Monday. Please have a look at the data already and maybe scroll through the paper with a focus on methods for data collection.
