### ISSUE TITLE
[data] Cap Haitien CBS Suitability Mapping

### ISSUE THREAD

**Issue by mayalubecks** [openwashdata/data#5]
I conducted a couple different suitability analyses in QGIS using several base layers (in both raster and shapefile format) and SOIL would love to share them publicly!

**Comment by larnsce** [comment]
Thank you @mayalubecks. We are so excited that you have decided to share your data. 

I have set everything up and your first tasks are described here: https://github.com/openwashdata/cbssuitabilityhaiti/issues/1

Looking forward to working with you on this.
