### ISSUE TITLE
[data]  Utility Performance Monitoring & Information System for piped water supply in Uganda

### ISSUE THREAD

**Issue by mianzg** [openwashdata/data#51]
http://upmis.geocodis.com

**Comment by kabega** [comment]
I've been following the UPMIS project and was very impressed with the frontend implementation at  https://upmis.geocodis.com/home . I am currently completing a dissertation on piped water supply monitoring in Uganda. Your project is highly relevant to my findings, and I’d love to cite your architectural approach. Would you be open to sharing a high-level overview of the tech stack and the database schema (tables/structue) for academic reference? I’m happy to cite your work formally or sign an NDA regarding the source code.
