### ISSUE TITLE
[data] Public waste skips in Blantyre Malawi

### ISSUE THREAD

**Issue by larnsce** [openwashdata/data#7]

**Comment by larnsce** [comment]
New dataset is @sebastian-loos @mianzg @mbannert 

https://github.com/Global-Health-Engineering/data-public-waste-skips-blantyre

It's already published as a website and is also stored on our GHE Organisation, but it could be packaged into an R package and with proper CSV and XLSX Download options.

We either keep the repo name the same (but change the package name) or we use a redirect to open a different website that's on openwashdata organisation.

**Comment by mianzg** [comment]
I don't understand the redirect part. 

Could we do this:
1. Fork the repo into openwashdata with a new repo name (e.g. "wasteskipsblantyre") which is the pkg name.
2. Convert the content into an openwashdata package. Refer the original repo in ReadMe if needed.
3. Use the published website as one of the example page?

**Comment by larnsce** [comment]
@mbannert @mianzg @sebastian-loos I had previously used the `dataspice` package to prepare data publications. They were not published as R data packages, but had a lot of great elements that we could re-use. 

I am thinking particularly of the `write_spice()` function, which writes metadata from a set of CSVs into the JSON-LD:

https://docs.ropensci.org/dataspice/reference/write_spice.html

Package:

https://docs.ropensci.org/dataspice/

We should review this workflow and adapt some of it to our own needs.

**Comment by larnsce** [comment]
> I don't understand the redirect part.

This index.html in the docs folder redirects to a the website hosted in openwashdata repo:

https://github.com/Global-Health-Engineering/data-public-waste-skips-blantyre/blob/main/docs/index.html

> Fork the repo into openwashdata with a new repo name (e.g. "wasteskipsblantyre") which is the pkg name.

Great! Done: https://github.com/openwashdata/wasteskipsblantyre

> Convert the content into an openwashdata package. Refer the original repo in ReadMe if needed.

No need to refer to original repo. We just need to see what happens when we publish a new release from openwashdata

> Use the published website as one of the example page?

The published website didn't look great, but the example page can have a map of the waste skip locations. That would probably be even better placed in the README.rmd. That's something @sebastian-loos can help with now. 

I have also added @M-Yesaya as a collaborator to the new repo.

**Comment by mianzg** [comment]
@sebastian-loos  I have created a new branch`pkg` to convert previous stuff into a package. Once it's merged, could you take it over with @M-Yesaya for the vignettes?

**Comment by sebastian-loos** [comment]
Hey @mianzg, yes of course.

@M-Yesaya don't worry. We can have a look into it, as soon as you got settled and your thesis is done..

**Comment by myesaya** [comment]
@sebastian

I will be ready for the discussions on Thursday or Friday. You let me know
the time that works for you.

**Comment by larnsce** [comment]
Thank you all for your work on this. 

I will go ahead and close the issue.
