### ISSUE TITLE
[data] UPGro programme on groundwater in Africa (2013 - 2021)

### ISSUE THREAD

**Issue by larnsce** [openwashdata/data#9]
**Project:**  Unlocking the Potential of Groundwater for the Poor programme 2013-2020
**Main Website:** https://upgro.org/ 

## Context

Any data generated had to be sent to a national data centre for publish disclosure after an embargo period. 

## Access 

- Directly from BGS (British Geolofical Survey). 15 records. Search term (upgro): https://webapps.bgs.ac.uk/services/ngdc/accessions/index.html?simpleText=upgro
- Related publications and data: https://upgro.org/publications-papers/data/

id | title | difficulty | format | include | details
-- | -- | -- | -- | -- | --
132765 | Weekly volume of water pumped for handpumps monitored with Smart Handpump technology, Kwale County, Kenya | low | XLSX | yes | https://webapps.bgs.ac.uk/services/ngdc/accessions/index.html?simpleText=upgro#item132765
42133 | Where does the water flow? Roads runoff, soil erosion, groundwater, livelohoods and poverty alleviation in Tigray, Ethiopia. June 2014 | high | PDF | no | https://webapps.bgs.ac.uk/services/ngdc/accessions/index.html?simpleText=upgro#item42133
76389 | Results of two sampling campaigns conducted in Kwale County Kenya in March and June 2016 by GHS/UPC as part of the Gro for GooD project (https://upgro.org/consortium/gro-for-good/) | medium | xlsx | no | https://webapps.bgs.ac.uk/services/ngdc/accessions/index.html?simpleText=upgro#item76389

**Comment by mianzg** [comment]
I contacted with the author of id 132765 dataset, and if nothing goes against it, I will convert this dataset.

I also didn't find direct licensing information for these datasets.

**Comment by larnsce** [comment]
It's a non-permissive Open Government License. 

![Screenshot 2023-08-09 at 09 21 36](https://github.com/openwashdata/data/assets/18212549/4d6aa6ad-59b6-4b5f-8ba3-fb70281c2073)

https://www.bgs.ac.uk/download/ngdc-terms-and-conditions/#

You can re-publish the package as CC-BY and can also reference the original license.

**Comment by mianzg** [comment]
For such a program, I am thinking later to build a package `upgro` as an umbrella package of its projects datasets? Just as `tidyverse`. I need to check `tidyverse` source code though. If it's feasible, we could apply to other bigger data source too. 

The alternative is to squeeze everything into a single package like r pkg `datasets`. The problem is that our data is not as simple as `datasets`. One project might span to multiple datasets. With this approach, we then may need some prefix to indicate which datasets belong to which project. 
@larnsce @sebastian-loos @mbannert

**Comment by larnsce** [comment]
Yes, that's generally a good idea. I think I have gone through all the 15 data resources by now and it seems like there are only 2 (a 3rd under embargo) that are worth publishing here.

@sebastian-loos might take one 76389 as his additional dataset for the remaining time. If he does, then I would stay let's keep it as two separate R packages, also to credit all the authors that were part of the original study.

For all openwashdata datasets, I had actually thought that we could rename the current `openwashdata` package and use that name as an umbrella package for all datasets. That would feel the most plausible that the R package openwashdata provides access to all underlying individual data packages.

**Comment by sebastian-loos** [comment]
@larnsce @mianzg 

Alright. I'll go ahead and take dataset 76389 as my additional dataset.

**Comment by sebastian-loos** [comment]
> I contacted with the author of id 132765 dataset, and if nothing goes against it, I will convert this dataset.
> 
> I also didn't find direct licensing information for these datasets.

Hey @mianzg, have you heard something from this author? Is it Rob Hope? He is also the author of dataset 76389^^

**Comment by mianzg** [comment]
Dr. Patrick Thomson is contacted and will be followed up as the collaborator for these datasets

**Comment by mianzg** [comment]
@larnsce `waterpumpkwale` package is ready for review: https://openwashdata.github.io/waterpumpkwale/

**Comment by larnsce** [comment]
Thanks, @mianzg. It looks good and documentation of the variables has great detail. 

A few notes:

- replace funding note with the ETH ORD program
- do you have a visualisation that you could add rightz before Installation?
- you could add an automated CMD BUILD check: `usethis::use_github_action_check_standard()`
- I get two warnings on devtools::check(). See if you can fix the warnings. You can ignores the notes.

Citation related

- the citation that shows up on the README does not show the year
- should I do the Zenodo DOI registration and update the citation?

**Comment by mianzg** [comment]
- [x] funding note (should I check all published pkgs? I copied this from previously published ones)
- [x] visualisation image
- [x] add CMD (can be a feature for openwashdata-dev @mbannert )
- [x] reproduce  devtools::check()
- [x] change citation year 
- [x] add to Zenodo

**Comment by mianzg** [comment]
- [ ] funding note (should I check all published pkgs? I copied this from previously published ones)
- [ ] visualisation image
- [ ] add CMD (can be a feature for openwashdata-dev @mbannert )
- [ ] reproduce  devtools::check()
- [ ] change citation year 
- [ ] add to Zenodo
